version: "3.9"

services:
  # MongoDB
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  # Redis
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  # API server
  api:
    build: .
    container_name: api
    command: node app.js
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - REDIS_TLS=false
      - MONGO_URI=mongodb://mongo:27017/bulkemailer
      - JWT_SECRET=adeb582f9b41d99614da5e47641463cc479fd202e1c35d3c8b99d4aed343a11f
    depends_on:
      - redis
      - mongo
    networks:
      - app-network

  # Worker service
  worker:
    build: .
    container_name: worker
    command: node worker.js
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - REDIS_TLS=false
      - MONGO_URI=mongodb://mongo:27017/bulkemailer
      - JWT_SECRET=adeb582f9b41d99614da5e47641463cc479fd202e1c35d3c8b99d4aed343a11f
    depends_on:
      - redis
      - mongo
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge
